package:
  name: plaidbench
  version: 0.5.0

build:
  entry_points:
    - plaidbench = plaidbench.cli:plaidbench
  include_recipe: False
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/8f/3b/b2fa2d815656e7b69b1d8d737865ac2dd48c656f34bca5642f116e9d0678/plaidbench-0.5.0-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click >=6.0.0
    - colorama
    - h5py >=2.7.0
    - numpy
    - plaidml
    - requests 2.18.4
    - six
    - unittest2
