package:
  name: onnx-plaidml
  version: 0.5.0

build:
  entry_points:
    - convert-onnx-to-tile = onnx_plaidml.conversion:onnx_to_tile
  include_recipe: False
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/20/f4/817cac51f5839102cc30747e66c50876f9ca37250b0f9136ddd57ab34413/onnx_plaidml-0.5.0-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - click
    - numpy
    - onnx 1.2.1
    - plaidml >=0.3.3
    - six
