package:
  name: plaidml
  version: 0.5.0

build:
  entry_points:
    - plaidml-setup = plaidml.plaidml_setup:main
  include_recipe: False
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/7b/a2/f35dcdbe8ee957f70000c7e32eca1fc9727e9c4abe6c65fef577e0092e3d/plaidml-0.5.0-py2.py3-none-win_amd64.whl # [win64]
  script: pip install --no-deps https://files.pythonhosted.org/packages/99/de/e1953313d8bba57e2445201e858d727a5d997495b790773bb440b771a3f1/plaidml-0.5.0-py2.py3-none-macosx_10_10_x86_64.whl # [osx]
  script: pip install --no-deps https://files.pythonhosted.org/packages/48/b7/5c019a8c64e92fc69c77f077e9a1bc6ea7883eb8fd79c639082c7984bfb5/plaidml-0.5.0-py2.py3-none-manylinux1_x86_64.whl # [linux64]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - requests
    - six
