package:
  name: plaidml-keras
  version: 0.5.0

build:
  include_recipe: False
  noarch: python
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/17/34/4102261e3d8867c31bae9f4def5d7e700fc25fff232fa1780040e8ed79b0/plaidml_keras-0.5.0-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - plaidml
    - keras 2.2.4
    - six
