package:
  name: keras
  version: 2.2.2

build:
  include_recipe: False
  noarch: python
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/34/7d/b1dedde8af99bd82f20ed7e9697aac0597de3049b1f786aa2aac3b9bd4da/Keras-2.2.2-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
    - pyyaml
    - h5py
    - keras-applications 1.0.4
    - keras-preprocessing 1.0.2
