package:
  name: keras
  version: 2.2.4

build:
  include_recipe: False
  noarch: python
  number: 0
  script: pip install --no-deps https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.1
    - scipy >=0.14
    - six >=1.9.0
    - pyyaml
    - h5py
    - keras-applications >=1.0.6
    - keras-preprocessing >=1.0.5
